"""
PAXIS Agent — Canonical Trade Objects
======================================
Defines the authoritative data contracts for the entire pipeline.

Every trade MUST flow through these typed objects:
  TradeCandidate  → generated by strategy (NO volume)
  ApprovedTrade   → approved by Risk Engine (WITH volume)
  TradeLeg        → individual partial-exit segment
  TradeLifecycleState → explicit state machine

No strategy may execute an order without an ApprovedTrade existing.
No ApprovedTrade may exist without passing through the Risk Engine.

Architecture:
  Strategy → TradeCandidate → Risk Engine → ApprovedTrade → ExecutionAuthority → MT5
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional


# ══════════════════════════════════════════════════════════════════════════════
# ENUMS
# ══════════════════════════════════════════════════════════════════════════════


class TradeLifecycleState(Enum):
    """Full state machine for every trade, from signal to exit."""
    MARKET_DATA       = "MARKET_DATA"
    SETUP_DETECTED    = "SETUP_DETECTED"
    CANDIDATE         = "CANDIDATE"
    QUALITY_CHECK     = "QUALITY_CHECK"
    RISK_CHECK        = "RISK_CHECK"
    APPROVED          = "APPROVED"
    EXECUTION_PENDING = "EXECUTION_PENDING"
    EXECUTED          = "EXECUTED"
    MANAGED           = "MANAGED"
    PARTIAL_EXIT      = "PARTIAL_EXIT"
    CLOSED            = "CLOSED"
    REJECTED          = "REJECTED"
    CANCELLED         = "CANCELLED"


class EntryMode(Enum):
    """Which entry mode produced this trade candidate."""
    STRUCTURAL     = "STRUCTURAL"    # Retracement into POI
    BREAKOUT       = "BREAKOUT"      # Confirmed BOS + displacement
    AUTO_SCALP     = "AUTO_SCALP"    # Short-term scalp
    BREAKOUT_RETEST = "BREAKOUT_RETEST"  # Breakout + micro-retest


class Direction(Enum):
    BUY  = "BUY"
    SELL = "SELL"


class StrategyFamily(Enum):
    SMC           = "SMC"
    ICT           = "ICT"
    AUTO_SCALP    = "AUTO_SCALP"
    BREAKOUT      = "BREAKOUT"


# ══════════════════════════════════════════════════════════════════════════════
# TRADE CANDIDATE
# ══════════════════════════════════════════════════════════════════════════════


@dataclass
class TradeCandidate:
    """
    Output of the strategy layer. Contains setup metadata but NO volume.
    Volume is determined exclusively by the Risk Engine.

    IMPORTANT: A strategy must NEVER set volume/lot_size.
    That responsibility belongs to the Risk Engine.
    """
    # Identity
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    symbol: str = ""
    direction: str = "BUY"           # "BUY" | "SELL"
    strategy: str = ""               # e.g. "SMC_OB_PULLBACK"
    strategy_family: str = "SMC"     # StrategyFamily value
    strategy_version: str = "1.0"
    entry_mode: str = "STRUCTURAL"   # EntryMode value

    # Timestamp
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    # Price levels (NO volume here)
    entry: float = 0.0
    stop_loss: float = 0.0
    tp1: Optional[float] = None
    tp2: Optional[float] = None
    tp3: Optional[float] = None

    # Quality scores
    setup_score: float = 0.0
    confluence_score: float = 0.0
    quality_grade: str = "NO_GRADE"  # "A+", "A", "B", "C", "REJECT"

    # Context
    regime: str = "UNKNOWN"
    session: str = "UNKNOWN"
    is_kill_zone: bool = False
    spread_pips: float = 0.0

    # Breakout-specific
    bos_confirmed: bool = False
    displacement_confirmed: bool = False
    displacement_atr_ratio: float = 0.0
    structure_id: Optional[str] = None  # Prevents duplicate entries on same BOS

    # Full traceability snapshot
    signal_features: Dict[str, Any] = field(default_factory=dict)
    regime_features: Dict[str, Any] = field(default_factory=dict)

    # Derived
    @property
    def rr_ratio(self) -> float:
        if not self.tp1 or self.entry <= 0 or self.stop_loss <= 0:
            return 0.0
        sl_dist = abs(self.entry - self.stop_loss)
        tp_dist = abs(self.tp1 - self.entry)
        return round(tp_dist / sl_dist, 2) if sl_dist > 0 else 0.0

    @property
    def sl_distance(self) -> float:
        return abs(self.entry - self.stop_loss)

    def is_valid(self) -> bool:
        """Basic structural validity check."""
        if self.entry <= 0 or self.stop_loss <= 0:
            return False
        if self.direction == "BUY" and self.stop_loss >= self.entry:
            return False
        if self.direction == "SELL" and self.stop_loss <= self.entry:
            return False
        if self.tp1 is not None:
            if self.direction == "BUY" and self.tp1 <= self.entry:
                return False
            if self.direction == "SELL" and self.tp1 >= self.entry:
                return False
        return True

    def to_dict(self) -> dict:
        return {
            "signal_id": self.signal_id,
            "symbol": self.symbol,
            "direction": self.direction,
            "strategy": self.strategy,
            "strategy_family": self.strategy_family,
            "entry_mode": self.entry_mode,
            "timestamp": self.timestamp.isoformat(),
            "entry": self.entry,
            "stop_loss": self.stop_loss,
            "tp1": self.tp1,
            "tp2": self.tp2,
            "tp3": self.tp3,
            "rr_ratio": self.rr_ratio,
            "setup_score": self.setup_score,
            "confluence_score": self.confluence_score,
            "quality_grade": self.quality_grade,
            "regime": self.regime,
            "session": self.session,
            "is_kill_zone": self.is_kill_zone,
            "spread_pips": self.spread_pips,
            "bos_confirmed": self.bos_confirmed,
            "displacement_confirmed": self.displacement_confirmed,
        }


# ══════════════════════════════════════════════════════════════════════════════
# APPROVED TRADE
# ══════════════════════════════════════════════════════════════════════════════


@dataclass
class ApprovedTrade:
    """
    Output of the Risk Engine. The ONLY object that permits MT5 execution.
    ExecutionAuthority checks isinstance(x, ApprovedTrade) before placing orders.

    Contains the original candidate PLUS broker-aware sizing.
    """
    candidate: TradeCandidate

    # Risk Engine outputs
    volume: float = 0.0
    allowed_risk_usd: float = 0.0
    actual_risk_usd: float = 0.0
    margin_required: Optional[float] = None

    # Broker constraints used
    broker_volume_step: float = 0.01
    broker_min_volume: float = 0.01
    broker_max_volume: float = 100.0
    broker_stops_level: int = 0

    # Risk calculation detail
    risk_pct: float = 0.0
    sl_distance_points: float = 0.0
    tick_value: float = 0.0
    contract_size: float = 0.0

    # Approval state
    risk_approved: bool = False
    rejection_reason: Optional[str] = None
    rejection_codes: List[str] = field(default_factory=list)

    # Environment that approved this
    environment: str = "PAPER"  # "DEVELOPMENT" | "PAPER" | "LIVE"

    # Versions at time of approval
    risk_engine_version: str = "2.0"
    config_hash: str = ""

    @property
    def signal_id(self) -> str:
        return self.candidate.signal_id

    @property
    def symbol(self) -> str:
        return self.candidate.symbol

    @property
    def direction(self) -> str:
        return self.candidate.direction

    @property
    def entry(self) -> float:
        return self.candidate.entry

    @property
    def stop_loss(self) -> float:
        return self.candidate.stop_loss

    @property
    def tp1(self) -> Optional[float]:
        return self.candidate.tp1

    @property
    def tp2(self) -> Optional[float]:
        return self.candidate.tp2

    def is_executable(self) -> bool:
        """Returns True only if this trade may proceed to MT5."""
        return (
            self.risk_approved
            and self.volume > 0
            and self.volume >= self.broker_min_volume
            and self.volume <= self.broker_max_volume
            and self.candidate.is_valid()
        )

    def to_dict(self) -> dict:
        d = self.candidate.to_dict()
        d.update({
            "volume": self.volume,
            "allowed_risk_usd": round(self.allowed_risk_usd, 4),
            "actual_risk_usd": round(self.actual_risk_usd, 4),
            "risk_pct": round(self.risk_pct, 4),
            "margin_required": self.margin_required,
            "broker_volume_step": self.broker_volume_step,
            "broker_min_volume": self.broker_min_volume,
            "risk_approved": self.risk_approved,
            "rejection_reason": self.rejection_reason,
            "rejection_codes": self.rejection_codes,
            "environment": self.environment,
            "risk_engine_version": self.risk_engine_version,
        })
        return d


# ══════════════════════════════════════════════════════════════════════════════
# TRADE LEG
# ══════════════════════════════════════════════════════════════════════════════


@dataclass
class TradeLeg:
    """
    One partial-exit segment of a position.
    Each leg books PnL IMMEDIATELY when it closes.

    Example:
        Trade #1001 — BUY XAUUSD 0.02 lots
        Leg 1: 0.01 lots closed at TP1 → PnL booked immediately
        Leg 2: 0.01 lots closed at SL  → PnL booked immediately
        Total trade PnL = Leg1.pnl_usd + Leg2.pnl_usd
    """
    leg_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    parent_signal_id: str = ""
    symbol: str = ""
    direction: str = "BUY"

    entry_price: float = 0.0
    exit_price: float = 0.0
    volume: float = 0.0
    lot_fraction: float = 1.0   # e.g. 0.5 for 50% of position

    entry_time: Optional[datetime] = None
    exit_time: Optional[datetime] = None

    pnl_usd: float = 0.0
    pnl_r: float = 0.0
    exit_reason: str = ""  # "TP1", "TP2", "SL", "BREAKEVEN", "TRAILING", "MANUAL", "TIMEOUT"

    commission_usd: float = 0.0
    spread_cost_usd: float = 0.0
    swap_usd: float = 0.0

    @property
    def net_pnl_usd(self) -> float:
        return self.pnl_usd - self.commission_usd - self.spread_cost_usd - abs(self.swap_usd)

    @property
    def holding_seconds(self) -> Optional[float]:
        if self.entry_time and self.exit_time:
            return (self.exit_time - self.entry_time).total_seconds()
        return None


# ══════════════════════════════════════════════════════════════════════════════
# PIPELINE CONTEXT
# ══════════════════════════════════════════════════════════════════════════════


@dataclass
class PipelineContext:
    """
    Full market context passed to all pipeline stages.
    Immutable snapshot — no stage should modify this.
    """
    symbol: str = ""
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    # Prices
    bid: float = 0.0
    ask: float = 0.0
    spread_pips: float = 0.0

    # SMC snapshots
    smc_4h: Dict[str, Any] = field(default_factory=dict)
    smc_1h: Dict[str, Any] = field(default_factory=dict)
    smc_15m: Dict[str, Any] = field(default_factory=dict)
    smc_1m: Dict[str, Any] = field(default_factory=dict)

    # Indicators
    indicators_4h: Optional[Any] = None
    indicators_1h: Optional[Any] = None
    indicators_15m: Optional[Any] = None
    indicators_1m: Optional[Any] = None

    # Session
    session: str = "UNKNOWN"
    is_kill_zone: bool = False
    session_dict: Dict[str, Any] = field(default_factory=dict)

    # Regime
    regime: str = "UNKNOWN"
    regime_confidence: float = 0.0
    regime_features: Dict[str, Any] = field(default_factory=dict)

    # Account state
    account_balance: float = 0.0
    account_equity: float = 0.0
    daily_pnl_usd: float = 0.0
    open_positions: List[dict] = field(default_factory=list)
    consecutive_losses: int = 0

    # News
    news_blocked: bool = False
    news_reason: str = ""

    # ATR reference (most useful timeframe)
    atr_1h: float = 1.0
    atr_15m: float = 0.5

    @property
    def mid_price(self) -> float:
        return (self.bid + self.ask) / 2.0

    @property
    def open_positions_count(self) -> int:
        return len(self.open_positions)

    def to_features_dict(self) -> dict:
        """For traceability — full snapshot of context."""
        return {
            "symbol": self.symbol,
            "timestamp": self.timestamp.isoformat(),
            "bid": self.bid,
            "ask": self.ask,
            "spread_pips": self.spread_pips,
            "session": self.session,
            "is_kill_zone": self.is_kill_zone,
            "regime": self.regime,
            "regime_confidence": self.regime_confidence,
            "account_balance": self.account_balance,
            "daily_pnl_usd": self.daily_pnl_usd,
            "open_positions_count": self.open_positions_count,
            "news_blocked": self.news_blocked,
            "atr_1h": self.atr_1h,
            "trend_4h": self.smc_4h.get("trend", "NEUTRAL"),
            "trend_1h": self.smc_1h.get("trend", "NEUTRAL"),
            "trend_15m": self.smc_15m.get("trend", "NEUTRAL"),
        }
